---
# handlers file for web
- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Restart audit
  shell: 'service auditd restart'